name: crd
 
on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter  code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
        
        
jobs:
  build:
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
& {$P = $env:TEMP + '\chromeremotedesktophost.msi'; Invoke-WebRequest 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi' -OutFile $P; Start-Process $P -Wait; Remove-Item $P}
& {$P = $env:TEMP + '\chrome_installer.exe'; Invoke-WebRequest 'https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi' -OutFile $P; Start-Process -FilePath msiexec -Args "/i $P /quiet" -Wait; Remove-Item $P}
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1
